version: '3.9'

services:
  update:
    image: gitlabterraformcontainer
    network_mode: host
    working_dir: /app
    environment:
      - TF_HTTP_USERNAME=${TF_HTTP_USERNAME}
      - TF_HTTP_PASSWORD=${TF_HTTP_PASSWORD}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_USERNAME=${GITLAB_USERNAME}
    entrypoint: ["sh", "-c"]
    command: ["terraform init && terraform validate && terraform apply -auto-approve"]
